// Displays AI insight messages generated by the backend.

const STYLES = {
    warning: 'bg-amber-50 border-amber-200 text-amber-800',
    success: 'bg-emerald-50 border-emerald-200 text-emerald-800',
    info: 'bg-sky-50 border-sky-200 text-sky-800',
};

const ICONS = { warning: '⚠️', success: '🎉', info: '💡' };

export default function InsightsPanel({ insights }) {
    return (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-5">
            <h3 className="font-semibold text-slate-900 mb-3">AI Insights</h3>
            {insights.length === 0 ? (
                <p className="text-sm text-slate-500">
                    No insights yet — add a few habits and start tracking to see suggestions.
                </p>
            ) : (
                <ul className="space-y-2">
                    {insights.map((ins, i) => (
                        <li
                            key={i}
                            className={`flex gap-2 items-start text-sm px-3 py-2 rounded-lg border ${
                                STYLES[ins.type] || STYLES.info
                            }`}
                        >
                            <span>{ICONS[ins.type] || ICONS.info}</span>
                            <span>{ins.message}</span>
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
}
